// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: joint_status.proto

#ifndef PROTOBUF_joint_5fstatus_2eproto__INCLUDED
#define PROTOBUF_joint_5fstatus_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace my_msgs {
namespace msgs {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_joint_5fstatus_2eproto();
void protobuf_AssignDesc_joint_5fstatus_2eproto();
void protobuf_ShutdownFile_joint_5fstatus_2eproto();

class JointStatusResponse;
class JointStatusResponse_JointStatus;

// ===================================================================

class JointStatusResponse_JointStatus : public ::google::protobuf::Message {
 public:
  JointStatusResponse_JointStatus();
  virtual ~JointStatusResponse_JointStatus();
  
  JointStatusResponse_JointStatus(const JointStatusResponse_JointStatus& from);
  
  inline JointStatusResponse_JointStatus& operator=(const JointStatusResponse_JointStatus& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const JointStatusResponse_JointStatus& default_instance();
  
  void Swap(JointStatusResponse_JointStatus* other);
  
  // implements Message ----------------------------------------------
  
  JointStatusResponse_JointStatus* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const JointStatusResponse_JointStatus& from);
  void MergeFrom(const JointStatusResponse_JointStatus& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  
  // required double position = 2;
  inline bool has_position() const;
  inline void clear_position();
  static const int kPositionFieldNumber = 2;
  inline double position() const;
  inline void set_position(double value);
  
  // required double velocity = 3;
  inline bool has_velocity() const;
  inline void clear_velocity();
  static const int kVelocityFieldNumber = 3;
  inline double velocity() const;
  inline void set_velocity(double value);
  
  // required double effort = 4;
  inline bool has_effort() const;
  inline void clear_effort();
  static const int kEffortFieldNumber = 4;
  inline double effort() const;
  inline void set_effort(double value);
  
  // @@protoc_insertion_point(class_scope:my_msgs.msgs.JointStatusResponse.JointStatus)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_position();
  inline void clear_has_position();
  inline void set_has_velocity();
  inline void clear_has_velocity();
  inline void set_has_effort();
  inline void clear_has_effort();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* name_;
  double position_;
  double velocity_;
  double effort_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_joint_5fstatus_2eproto();
  friend void protobuf_AssignDesc_joint_5fstatus_2eproto();
  friend void protobuf_ShutdownFile_joint_5fstatus_2eproto();
  
  void InitAsDefaultInstance();
  static JointStatusResponse_JointStatus* default_instance_;
};
// -------------------------------------------------------------------

class JointStatusResponse : public ::google::protobuf::Message {
 public:
  JointStatusResponse();
  virtual ~JointStatusResponse();
  
  JointStatusResponse(const JointStatusResponse& from);
  
  inline JointStatusResponse& operator=(const JointStatusResponse& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const JointStatusResponse& default_instance();
  
  void Swap(JointStatusResponse* other);
  
  // implements Message ----------------------------------------------
  
  JointStatusResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const JointStatusResponse& from);
  void MergeFrom(const JointStatusResponse& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef JointStatusResponse_JointStatus JointStatus;
  
  // accessors -------------------------------------------------------
  
  // repeated .my_msgs.msgs.JointStatusResponse.JointStatus joint = 1;
  inline int joint_size() const;
  inline void clear_joint();
  static const int kJointFieldNumber = 1;
  inline const ::my_msgs::msgs::JointStatusResponse_JointStatus& joint(int index) const;
  inline ::my_msgs::msgs::JointStatusResponse_JointStatus* mutable_joint(int index);
  inline ::my_msgs::msgs::JointStatusResponse_JointStatus* add_joint();
  inline const ::google::protobuf::RepeatedPtrField< ::my_msgs::msgs::JointStatusResponse_JointStatus >&
      joint() const;
  inline ::google::protobuf::RepeatedPtrField< ::my_msgs::msgs::JointStatusResponse_JointStatus >*
      mutable_joint();
  
  // @@protoc_insertion_point(class_scope:my_msgs.msgs.JointStatusResponse)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::my_msgs::msgs::JointStatusResponse_JointStatus > joint_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_joint_5fstatus_2eproto();
  friend void protobuf_AssignDesc_joint_5fstatus_2eproto();
  friend void protobuf_ShutdownFile_joint_5fstatus_2eproto();
  
  void InitAsDefaultInstance();
  static JointStatusResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// JointStatusResponse_JointStatus

// required string name = 1;
inline bool JointStatusResponse_JointStatus::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void JointStatusResponse_JointStatus::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void JointStatusResponse_JointStatus::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void JointStatusResponse_JointStatus::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& JointStatusResponse_JointStatus::name() const {
  return *name_;
}
inline void JointStatusResponse_JointStatus::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void JointStatusResponse_JointStatus::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void JointStatusResponse_JointStatus::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* JointStatusResponse_JointStatus::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* JointStatusResponse_JointStatus::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required double position = 2;
inline bool JointStatusResponse_JointStatus::has_position() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void JointStatusResponse_JointStatus::set_has_position() {
  _has_bits_[0] |= 0x00000002u;
}
inline void JointStatusResponse_JointStatus::clear_has_position() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void JointStatusResponse_JointStatus::clear_position() {
  position_ = 0;
  clear_has_position();
}
inline double JointStatusResponse_JointStatus::position() const {
  return position_;
}
inline void JointStatusResponse_JointStatus::set_position(double value) {
  set_has_position();
  position_ = value;
}

// required double velocity = 3;
inline bool JointStatusResponse_JointStatus::has_velocity() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void JointStatusResponse_JointStatus::set_has_velocity() {
  _has_bits_[0] |= 0x00000004u;
}
inline void JointStatusResponse_JointStatus::clear_has_velocity() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void JointStatusResponse_JointStatus::clear_velocity() {
  velocity_ = 0;
  clear_has_velocity();
}
inline double JointStatusResponse_JointStatus::velocity() const {
  return velocity_;
}
inline void JointStatusResponse_JointStatus::set_velocity(double value) {
  set_has_velocity();
  velocity_ = value;
}

// required double effort = 4;
inline bool JointStatusResponse_JointStatus::has_effort() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void JointStatusResponse_JointStatus::set_has_effort() {
  _has_bits_[0] |= 0x00000008u;
}
inline void JointStatusResponse_JointStatus::clear_has_effort() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void JointStatusResponse_JointStatus::clear_effort() {
  effort_ = 0;
  clear_has_effort();
}
inline double JointStatusResponse_JointStatus::effort() const {
  return effort_;
}
inline void JointStatusResponse_JointStatus::set_effort(double value) {
  set_has_effort();
  effort_ = value;
}

// -------------------------------------------------------------------

// JointStatusResponse

// repeated .my_msgs.msgs.JointStatusResponse.JointStatus joint = 1;
inline int JointStatusResponse::joint_size() const {
  return joint_.size();
}
inline void JointStatusResponse::clear_joint() {
  joint_.Clear();
}
inline const ::my_msgs::msgs::JointStatusResponse_JointStatus& JointStatusResponse::joint(int index) const {
  return joint_.Get(index);
}
inline ::my_msgs::msgs::JointStatusResponse_JointStatus* JointStatusResponse::mutable_joint(int index) {
  return joint_.Mutable(index);
}
inline ::my_msgs::msgs::JointStatusResponse_JointStatus* JointStatusResponse::add_joint() {
  return joint_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::my_msgs::msgs::JointStatusResponse_JointStatus >&
JointStatusResponse::joint() const {
  return joint_;
}
inline ::google::protobuf::RepeatedPtrField< ::my_msgs::msgs::JointStatusResponse_JointStatus >*
JointStatusResponse::mutable_joint() {
  return &joint_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace my_msgs

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_joint_5fstatus_2eproto__INCLUDED
