// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "joint_status.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace my_msgs {
namespace msgs {

namespace {

const ::google::protobuf::Descriptor* JointStatusResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  JointStatusResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* JointStatusResponse_JointStatus_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  JointStatusResponse_JointStatus_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_joint_5fstatus_2eproto() {
  protobuf_AddDesc_joint_5fstatus_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "joint_status.proto");
  GOOGLE_CHECK(file != NULL);
  JointStatusResponse_descriptor_ = file->message_type(0);
  static const int JointStatusResponse_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointStatusResponse, joint_),
  };
  JointStatusResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      JointStatusResponse_descriptor_,
      JointStatusResponse::default_instance_,
      JointStatusResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointStatusResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointStatusResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(JointStatusResponse));
  JointStatusResponse_JointStatus_descriptor_ = JointStatusResponse_descriptor_->nested_type(0);
  static const int JointStatusResponse_JointStatus_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointStatusResponse_JointStatus, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointStatusResponse_JointStatus, position_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointStatusResponse_JointStatus, velocity_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointStatusResponse_JointStatus, effort_),
  };
  JointStatusResponse_JointStatus_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      JointStatusResponse_JointStatus_descriptor_,
      JointStatusResponse_JointStatus::default_instance_,
      JointStatusResponse_JointStatus_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointStatusResponse_JointStatus, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointStatusResponse_JointStatus, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(JointStatusResponse_JointStatus));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_joint_5fstatus_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    JointStatusResponse_descriptor_, &JointStatusResponse::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    JointStatusResponse_JointStatus_descriptor_, &JointStatusResponse_JointStatus::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_joint_5fstatus_2eproto() {
  delete JointStatusResponse::default_instance_;
  delete JointStatusResponse_reflection_;
  delete JointStatusResponse_JointStatus::default_instance_;
  delete JointStatusResponse_JointStatus_reflection_;
}

void protobuf_AddDesc_joint_5fstatus_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022joint_status.proto\022\014my_msgs.msgs\"\244\001\n\023J"
    "ointStatusResponse\022<\n\005joint\030\001 \003(\0132-.my_m"
    "sgs.msgs.JointStatusResponse.JointStatus"
    "\032O\n\013JointStatus\022\014\n\004name\030\001 \002(\t\022\020\n\010positio"
    "n\030\002 \002(\001\022\020\n\010velocity\030\003 \002(\001\022\016\n\006effort\030\004 \002("
    "\001", 201);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "joint_status.proto", &protobuf_RegisterTypes);
  JointStatusResponse::default_instance_ = new JointStatusResponse();
  JointStatusResponse_JointStatus::default_instance_ = new JointStatusResponse_JointStatus();
  JointStatusResponse::default_instance_->InitAsDefaultInstance();
  JointStatusResponse_JointStatus::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_joint_5fstatus_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_joint_5fstatus_2eproto {
  StaticDescriptorInitializer_joint_5fstatus_2eproto() {
    protobuf_AddDesc_joint_5fstatus_2eproto();
  }
} static_descriptor_initializer_joint_5fstatus_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int JointStatusResponse_JointStatus::kNameFieldNumber;
const int JointStatusResponse_JointStatus::kPositionFieldNumber;
const int JointStatusResponse_JointStatus::kVelocityFieldNumber;
const int JointStatusResponse_JointStatus::kEffortFieldNumber;
#endif  // !_MSC_VER

JointStatusResponse_JointStatus::JointStatusResponse_JointStatus()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void JointStatusResponse_JointStatus::InitAsDefaultInstance() {
}

JointStatusResponse_JointStatus::JointStatusResponse_JointStatus(const JointStatusResponse_JointStatus& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void JointStatusResponse_JointStatus::SharedCtor() {
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  position_ = 0;
  velocity_ = 0;
  effort_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

JointStatusResponse_JointStatus::~JointStatusResponse_JointStatus() {
  SharedDtor();
}

void JointStatusResponse_JointStatus::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (this != default_instance_) {
  }
}

void JointStatusResponse_JointStatus::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* JointStatusResponse_JointStatus::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return JointStatusResponse_JointStatus_descriptor_;
}

const JointStatusResponse_JointStatus& JointStatusResponse_JointStatus::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_joint_5fstatus_2eproto();  return *default_instance_;
}

JointStatusResponse_JointStatus* JointStatusResponse_JointStatus::default_instance_ = NULL;

JointStatusResponse_JointStatus* JointStatusResponse_JointStatus::New() const {
  return new JointStatusResponse_JointStatus;
}

void JointStatusResponse_JointStatus::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
    position_ = 0;
    velocity_ = 0;
    effort_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool JointStatusResponse_JointStatus::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(17)) goto parse_position;
        break;
      }
      
      // required double position = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_position:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &position_)));
          set_has_position();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(25)) goto parse_velocity;
        break;
      }
      
      // required double velocity = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_velocity:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &velocity_)));
          set_has_velocity();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(33)) goto parse_effort;
        break;
      }
      
      // required double effort = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_effort:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &effort_)));
          set_has_effort();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void JointStatusResponse_JointStatus::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(), output);
  }
  
  // required double position = 2;
  if (has_position()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->position(), output);
  }
  
  // required double velocity = 3;
  if (has_velocity()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->velocity(), output);
  }
  
  // required double effort = 4;
  if (has_effort()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->effort(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* JointStatusResponse_JointStatus::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }
  
  // required double position = 2;
  if (has_position()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->position(), target);
  }
  
  // required double velocity = 3;
  if (has_velocity()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->velocity(), target);
  }
  
  // required double effort = 4;
  if (has_effort()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->effort(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int JointStatusResponse_JointStatus::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }
    
    // required double position = 2;
    if (has_position()) {
      total_size += 1 + 8;
    }
    
    // required double velocity = 3;
    if (has_velocity()) {
      total_size += 1 + 8;
    }
    
    // required double effort = 4;
    if (has_effort()) {
      total_size += 1 + 8;
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void JointStatusResponse_JointStatus::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const JointStatusResponse_JointStatus* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const JointStatusResponse_JointStatus*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void JointStatusResponse_JointStatus::MergeFrom(const JointStatusResponse_JointStatus& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_position()) {
      set_position(from.position());
    }
    if (from.has_velocity()) {
      set_velocity(from.velocity());
    }
    if (from.has_effort()) {
      set_effort(from.effort());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void JointStatusResponse_JointStatus::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void JointStatusResponse_JointStatus::CopyFrom(const JointStatusResponse_JointStatus& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JointStatusResponse_JointStatus::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;
  
  return true;
}

void JointStatusResponse_JointStatus::Swap(JointStatusResponse_JointStatus* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(position_, other->position_);
    std::swap(velocity_, other->velocity_);
    std::swap(effort_, other->effort_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata JointStatusResponse_JointStatus::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = JointStatusResponse_JointStatus_descriptor_;
  metadata.reflection = JointStatusResponse_JointStatus_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int JointStatusResponse::kJointFieldNumber;
#endif  // !_MSC_VER

JointStatusResponse::JointStatusResponse()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void JointStatusResponse::InitAsDefaultInstance() {
}

JointStatusResponse::JointStatusResponse(const JointStatusResponse& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void JointStatusResponse::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

JointStatusResponse::~JointStatusResponse() {
  SharedDtor();
}

void JointStatusResponse::SharedDtor() {
  if (this != default_instance_) {
  }
}

void JointStatusResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* JointStatusResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return JointStatusResponse_descriptor_;
}

const JointStatusResponse& JointStatusResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_joint_5fstatus_2eproto();  return *default_instance_;
}

JointStatusResponse* JointStatusResponse::default_instance_ = NULL;

JointStatusResponse* JointStatusResponse::New() const {
  return new JointStatusResponse;
}

void JointStatusResponse::Clear() {
  joint_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool JointStatusResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .my_msgs.msgs.JointStatusResponse.JointStatus joint = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_joint:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_joint()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_joint;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void JointStatusResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .my_msgs.msgs.JointStatusResponse.JointStatus joint = 1;
  for (int i = 0; i < this->joint_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->joint(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* JointStatusResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .my_msgs.msgs.JointStatusResponse.JointStatus joint = 1;
  for (int i = 0; i < this->joint_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->joint(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int JointStatusResponse::ByteSize() const {
  int total_size = 0;
  
  // repeated .my_msgs.msgs.JointStatusResponse.JointStatus joint = 1;
  total_size += 1 * this->joint_size();
  for (int i = 0; i < this->joint_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->joint(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void JointStatusResponse::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const JointStatusResponse* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const JointStatusResponse*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void JointStatusResponse::MergeFrom(const JointStatusResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  joint_.MergeFrom(from.joint_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void JointStatusResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void JointStatusResponse::CopyFrom(const JointStatusResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JointStatusResponse::IsInitialized() const {
  
  for (int i = 0; i < joint_size(); i++) {
    if (!this->joint(i).IsInitialized()) return false;
  }
  return true;
}

void JointStatusResponse::Swap(JointStatusResponse* other) {
  if (other != this) {
    joint_.Swap(&other->joint_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata JointStatusResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = JointStatusResponse_descriptor_;
  metadata.reflection = JointStatusResponse_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace my_msgs

// @@protoc_insertion_point(global_scope)
