// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "joint_effort_cmd.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace my_msgs {
namespace msgs {

namespace {

const ::google::protobuf::Descriptor* JointEffortCmdRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  JointEffortCmdRequest_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_joint_5feffort_5fcmd_2eproto() {
  protobuf_AddDesc_joint_5feffort_5fcmd_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "joint_effort_cmd.proto");
  GOOGLE_CHECK(file != NULL);
  JointEffortCmdRequest_descriptor_ = file->message_type(0);
  static const int JointEffortCmdRequest_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointEffortCmdRequest, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointEffortCmdRequest, effort_),
  };
  JointEffortCmdRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      JointEffortCmdRequest_descriptor_,
      JointEffortCmdRequest::default_instance_,
      JointEffortCmdRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointEffortCmdRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointEffortCmdRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(JointEffortCmdRequest));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_joint_5feffort_5fcmd_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    JointEffortCmdRequest_descriptor_, &JointEffortCmdRequest::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_joint_5feffort_5fcmd_2eproto() {
  delete JointEffortCmdRequest::default_instance_;
  delete JointEffortCmdRequest_reflection_;
}

void protobuf_AddDesc_joint_5feffort_5fcmd_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\026joint_effort_cmd.proto\022\014my_msgs.msgs\"5"
    "\n\025JointEffortCmdRequest\022\014\n\004name\030\001 \003(\t\022\016\n"
    "\006effort\030\002 \003(\001", 93);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "joint_effort_cmd.proto", &protobuf_RegisterTypes);
  JointEffortCmdRequest::default_instance_ = new JointEffortCmdRequest();
  JointEffortCmdRequest::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_joint_5feffort_5fcmd_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_joint_5feffort_5fcmd_2eproto {
  StaticDescriptorInitializer_joint_5feffort_5fcmd_2eproto() {
    protobuf_AddDesc_joint_5feffort_5fcmd_2eproto();
  }
} static_descriptor_initializer_joint_5feffort_5fcmd_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int JointEffortCmdRequest::kNameFieldNumber;
const int JointEffortCmdRequest::kEffortFieldNumber;
#endif  // !_MSC_VER

JointEffortCmdRequest::JointEffortCmdRequest()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void JointEffortCmdRequest::InitAsDefaultInstance() {
}

JointEffortCmdRequest::JointEffortCmdRequest(const JointEffortCmdRequest& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void JointEffortCmdRequest::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

JointEffortCmdRequest::~JointEffortCmdRequest() {
  SharedDtor();
}

void JointEffortCmdRequest::SharedDtor() {
  if (this != default_instance_) {
  }
}

void JointEffortCmdRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* JointEffortCmdRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return JointEffortCmdRequest_descriptor_;
}

const JointEffortCmdRequest& JointEffortCmdRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_joint_5feffort_5fcmd_2eproto();  return *default_instance_;
}

JointEffortCmdRequest* JointEffortCmdRequest::default_instance_ = NULL;

JointEffortCmdRequest* JointEffortCmdRequest::New() const {
  return new JointEffortCmdRequest;
}

void JointEffortCmdRequest::Clear() {
  name_.Clear();
  effort_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool JointEffortCmdRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->name(0).data(), this->name(0).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_name;
        if (input->ExpectTag(17)) goto parse_effort;
        break;
      }
      
      // repeated double effort = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_effort:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 17, input, this->mutable_effort())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_effort())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(17)) goto parse_effort;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void JointEffortCmdRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated string name = 1;
  for (int i = 0; i < this->name_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->name(i).data(), this->name(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(i), output);
  }
  
  // repeated double effort = 2;
  for (int i = 0; i < this->effort_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(
      2, this->effort(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* JointEffortCmdRequest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated string name = 1;
  for (int i = 0; i < this->name_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name(i).data(), this->name(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->name(i), target);
  }
  
  // repeated double effort = 2;
  for (int i = 0; i < this->effort_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleToArray(2, this->effort(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int JointEffortCmdRequest::ByteSize() const {
  int total_size = 0;
  
  // repeated string name = 1;
  total_size += 1 * this->name_size();
  for (int i = 0; i < this->name_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->name(i));
  }
  
  // repeated double effort = 2;
  {
    int data_size = 0;
    data_size = 8 * this->effort_size();
    total_size += 1 * this->effort_size() + data_size;
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void JointEffortCmdRequest::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const JointEffortCmdRequest* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const JointEffortCmdRequest*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void JointEffortCmdRequest::MergeFrom(const JointEffortCmdRequest& from) {
  GOOGLE_CHECK_NE(&from, this);
  name_.MergeFrom(from.name_);
  effort_.MergeFrom(from.effort_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void JointEffortCmdRequest::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void JointEffortCmdRequest::CopyFrom(const JointEffortCmdRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JointEffortCmdRequest::IsInitialized() const {
  
  return true;
}

void JointEffortCmdRequest::Swap(JointEffortCmdRequest* other) {
  if (other != this) {
    name_.Swap(&other->name_);
    effort_.Swap(&other->effort_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata JointEffortCmdRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = JointEffortCmdRequest_descriptor_;
  metadata.reflection = JointEffortCmdRequest_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace my_msgs

// @@protoc_insertion_point(global_scope)
